import { z } from 'zod';

import { corpus } from '../../corpus';
import type { GenerateContext } from './context';
import { generateFromZod } from './zod';

/**
 * The nine prompts with no machine-readable output schema (seven carry only a
 * human-readable `schema_for_llm`, two nothing). Each is written here as the
 * shape its caller reads - from `schema_for_llm` and the consuming code -
 * and generated by the same code as the Zod prompts. The every-prompt test
 * checks each one through the app's own parsing.
 */

const confidence = z.enum(['high', 'medium', 'low']);

/** `canon-extraction` → `server/canon-actions.ts` reads `data.extraction`. */
const canonExtraction = z.object({
  extraction: z.object({
    immutableEvents: z.array(
      z.object({
        type: z.enum([
          'death',
          'world_fact',
          'relationship',
          'timeline',
          'ability_loss',
          'location_destruction',
        ]),
        eventKey: z.string(),
        description: z.string(),
        confidence,
      }),
    ),
    characterStateChanges: z.array(
      z.object({
        characterName: z.string(),
        stateType: z.enum([
          'emotional',
          'physical',
          'relationship',
          'knowledge',
          'ability',
          'location',
          'goal',
        ]),
        fromState: z.string(),
        toState: z.string(),
        triggerEvent: z.string(),
      }),
    ),
    threadUpdates: z.array(
      z.object({
        threadName: z.string(),
        threadType: z.enum([
          'plot',
          'character',
          'mystery',
          'romantic',
          'conflict',
          'thematic',
        ]),
        action: z.enum(['open', 'progress', 'resolve']),
        description: z.string(),
        promises: z.array(z.string()).optional(),
      }),
    ),
    episodeSummary: z.string(),
    sentimentScore: z.number().min(0).max(1),
    keyEvents: z.array(z.string()).min(3).max(5),
  }),
});

/** `documentary/fact-checker-role` → `lib/documentary/fact-checker.ts` reads `data.fact_check`. */
const factChecker = z.object({
  fact_check: z.object({
    overall_verdict: z.enum(['pass', 'fail', 'warnings']),
    accuracy_score: z.number().min(0).max(1),
    total_claims_found: z.number().int().min(1).max(12),
    verified_claims: z.number().int().min(0).max(12),
    issues: z.array(
      z.object({
        severity: z.enum(['critical', 'warning', 'minor', 'info']),
        claim_in_content: z.string(),
        issue_type: z.enum([
          'inaccurate',
          'unsourced',
          'misrepresented',
          'citation_error',
          'missing_claim',
        ]),
        explanation: z.string(),
        verified_fact: z.string(),
        suggestion: z.string(),
      }),
    ),
    missing_required_claims: z.array(z.string()),
    citations_valid: z.boolean(),
    summary: z.string(),
  }),
});

/** `documentary/researcher-role` → `lib/documentary/researcher.ts` reads `data.research`. */
const researcher = z.object({
  research: z.object({
    topic_summary: z.string(),
    claims: z.array(
      z.object({
        claim: z.string(),
        category: z.string(),
        matched_fact_id: z.null(),
        confidence: z.enum(['verified', 'needs_source']),
        priority: z.enum(['critical', 'important', 'nice_to_have']),
        suggested_search: z.string(),
      }),
    ),
    research_gaps: z.array(z.string()),
    recommended_sources: z.array(z.string()),
  }),
});

/** `movie/act-context-extraction` → `agent/skills/act-context-skill.ts` reads `data.bridge`. */
const actContext = z.object({
  bridge: z.object({
    actNumber: z.number().int().min(1).max(5),
    actTitle: z.string(),
    characterStates: z.array(
      z.object({
        name: z.string(),
        isAlive: z.boolean(),
        emotionalState: z.string(),
        location: z.string(),
      }),
    ),
    openThreads: z.array(z.string()),
    resolvedThreads: z.array(z.string()),
    promises: z.array(z.string()),
    currentLocation: z.object({
      name: z.string(),
      presentCharacters: z.array(z.string()),
    }),
    toneVector: z.object({
      tension: z.number().min(0).max(1),
      humor: z.number().min(0).max(1),
      drama: z.number().min(0).max(1),
    }),
    stakesLevel: z.number().int().min(1).max(10),
    tensionLevel: z.number().int().min(1).max(10),
    carryForwardContext: z.string(),
  }),
});

/**
 * The four `news-generation` prompts stay registered although their callers
 * (the news services) were deleted in FILM-1902; the shapes below are what
 * those callers read.
 *
 * `news-generation/anchor-role` (AnchorScript).
 */
const anchor = z.object({
  script: z.array(
    z.object({
      type: z.enum(['ANCHOR', 'GRAPHIC', 'TRANSITION']),
      content: z.string(),
      durationSeconds: z.number().int().min(4).max(45).optional(),
      sources: z.array(z.string()).optional(),
    }),
  ),
  sourcesUsed: z.array(z.string()),
});

/** `news-generation/entity-extraction`. */
const entities = z.object({
  people: z.array(z.object({ name: z.string(), role: z.string().optional() })),
  organizations: z.array(
    z.object({ name: z.string(), type: z.string().optional() }),
  ),
  locations: z.array(
    z.object({ name: z.string(), type: z.enum(['city', 'country', 'region']) }),
  ),
  topics: z.array(z.string()),
  events: z.array(z.object({ name: z.string(), date: z.string().optional() })),
});

/** `news-generation/producer-role` (EpisodeRundown). */
const producer = z.object({
  rundown: z.array(
    z.object({
      segmentNumber: z.number().int().min(1).max(8),
      title: z.string(),
      duration: z.number().int().min(20).max(180),
      category: z.string(),
      searchQuery: z.string(),
      priority: z.enum(['high', 'medium', 'low']),
    }),
  ),
  totalRuntime: z.number().int().min(60).max(900),
});

/** `news-generation/topic-summary`: the caller read `data.summary`. */
const topicSummary = z.object({ summary: z.string() });

/** The template-generated prompts, by registry key, with the shape each emits. */
export const TEMPLATE_SCHEMAS: Record<string, z.ZodTypeAny> = {
  'canon-extraction': canonExtraction,
  'documentary/fact-checker-role': factChecker,
  'documentary/researcher-role': researcher,
  'movie/act-context-extraction': actContext,
  'news-generation/anchor-role': anchor,
  'news-generation/entity-extraction': entities,
  'news-generation/producer-role': producer,
  'news-generation/topic-summary': topicSummary,
};

/**
 * `dialogue-translation` is plain text: one numbered line per numbered input
 * line, `N. [tone] text`, which `agent/skills/translation-skill.ts` splits on
 * newlines and strips of its number.
 */
export function dialogueTranslation(userPrompt: string, ctx: GenerateContext) {
  const numbered = [...userPrompt.matchAll(/^\s*(\d+)[.)]\s+\S/gm)].map((m) =>
    Number(m[1]),
  );
  const count = numbered.length > 0 ? numbered.length : ctx.rng.int(2, 5);

  return Array.from(
    { length: count },
    (_, i) =>
      `${numbered[i] ?? i + 1}. [${ctx.rng.pick(corpus.emotions)}] ${ctx.rng.pick(corpus.dialogue)}`,
  ).join('\n');
}

export const TEXT_TEMPLATES: Record<
  string,
  (userPrompt: string, ctx: GenerateContext) => string
> = {
  'dialogue-translation': dialogueTranslation,
};

export function generateTemplate(
  key: string,
  userPrompt: string,
  ctx: GenerateContext,
) {
  const text = TEXT_TEMPLATES[key];
  if (text) return text(userPrompt, ctx);

  const schema = TEMPLATE_SCHEMAS[key];
  if (!schema) return undefined;

  return schema.parse(generateFromZod(schema, ctx));
}
