import { z } from 'zod';

/**
 * Batch Episode Creation Schemas (FILM-314)
 *
 * Zod schemas for validating input to batch episode creation actions.
 * Enables creating 2-24 episodes in a single batch with AI-generated outlines.
 */

// ============================================================
// Arc Position Schema
// ============================================================

/**
 * Story arc position for episode in season structure
 * Applied based on episode position in the season
 */
export const ArcPositionSchema = z.enum([
  'setup',
  'rising',
  'midpoint',
  'climax',
  'resolution',
]);

export type ArcPosition = z.infer<typeof ArcPositionSchema>;

// ============================================================
// Episode Outline Schema (LLM Output)
// ============================================================

/**
 * Single episode outline generated by LLM
 * Used for both generation output and batch creation input
 */
export const EpisodeOutlineSchema = z.object({
  number: z.number().int().positive(),
  title: z.string().min(1).max(255),
  premise: z.string().min(10).max(500),
  mainPlot: z.string().min(20).max(1000),
  characterFocus: z.array(z.string()).optional(),
  arcPosition: ArcPositionSchema,
});

export type EpisodeOutline = z.infer<typeof EpisodeOutlineSchema>;

// ============================================================
// Generate Season Outline Schema
// ============================================================

/**
 * Schema for generating season episode outlines via LLM
 * Creates 2-24 episode outlines from a season premise
 */
export const GenerateSeasonOutlineSchema = z.object({
  projectId: z.string().uuid(),
  seasonId: z.string().uuid().optional(),
  seasonPremise: z
    .string()
    .min(20, 'Season premise must be at least 20 characters')
    .max(2000, 'Season premise must be at most 2000 characters'),
  episodeCount: z
    .number()
    .int()
    .min(2, 'Must create at least 2 episodes')
    .max(24, 'Cannot create more than 24 episodes'),
  startingNumber: z.number().int().positive().default(1),
  genre: z.string().max(100).optional(),
  style: z.string().max(100).optional(),
});

export type GenerateSeasonOutlineInput = z.infer<
  typeof GenerateSeasonOutlineSchema
>;

// ============================================================
// Batch Create Episodes Schema
// ============================================================

/**
 * Schema for batch creating episodes from generated outlines
 * Inserts all episodes atomically
 */
export const BatchCreateEpisodesSchema = z.object({
  projectId: z.string().uuid(),
  seasonId: z.string().uuid().optional(),
  episodes: z
    .array(EpisodeOutlineSchema)
    .min(1, 'Must create at least 1 episode')
    .max(24, 'Cannot create more than 24 episodes at once'),
});

export type BatchCreateEpisodesInput = z.infer<
  typeof BatchCreateEpisodesSchema
>;

// ============================================================
// Regenerate Episode Outline Schema
// ============================================================

/**
 * Schema for regenerating a single episode outline with context
 * Uses surrounding episodes for narrative continuity
 */
export const RegenerateEpisodeOutlineSchema = z.object({
  projectId: z.string().uuid(),
  seasonId: z.string().uuid().optional(),
  episodeNumber: z.number().int().positive(),
  seasonPremise: z.string().min(20).max(2000),
  surroundingEpisodes: z.array(EpisodeOutlineSchema).optional(),
  additionalContext: z.string().max(500).optional(),
});

export type RegenerateEpisodeOutlineInput = z.infer<
  typeof RegenerateEpisodeOutlineSchema
>;

// ============================================================
// Response Types
// ============================================================

/**
 * Response from season outline generation
 */
export interface GenerateSeasonOutlineResponse {
  success: boolean;
  episodes: EpisodeOutline[];
  metadata: {
    provider: string;
    model: string;
    costCents: number;
    tokensUsed: number;
    generatedAt: string;
  };
}

/**
 * Response from batch episode creation
 */
export interface BatchCreateEpisodesResponse {
  success: boolean;
  episodes: Array<{
    id: string;
    number: number;
    title: string;
    status: string;
  }>;
  count: number;
}

/**
 * Response from episode outline regeneration
 */
export interface RegenerateEpisodeOutlineResponse {
  success: boolean;
  episode: EpisodeOutline;
  metadata: {
    provider: string;
    model: string;
    costCents: number;
    tokensUsed: number;
    generatedAt: string;
  };
}
