/*
 * -------------------------------------------------------
 * Section: Semantic search embeddings
 * Vector embeddings for episodes and characters, used by semantic
 * similarity search.
 *
 * These tables were originally created in
 * migrations/20251213000000_add_voyage_embeddings.sql with no counterpart
 * here. `config.toml` sets schema_paths = ["./schemas/*.sql"], so `db diff`
 * treated them as objects that ought not to exist and would have proposed
 * dropping them. They are declared here so the declarative schema and the
 * database agree.
 *
 * They were also created without RLS. Every table in `public` grants
 * `authenticated` full DML by default, so RLS is the only thing scoping a
 * table to its tenant — which meant any signed-in user of any account could
 * read, modify, delete or truncate every account's embeddings.
 * -------------------------------------------------------
 */

create extension if not exists vector;

/*
 * Episode embeddings
 */
create table if not exists public.episode_embeddings (
  episode_id uuid primary key references public.episodes(id) on delete cascade,
  premise_embedding vector(1024),
  story_embedding vector(1024),
  updated_at timestamp default now()
);

alter table public.episode_embeddings enable row level security;

/*
 * Character embeddings. `character_id` references assets, not a characters
 * table — characters are assets in this schema.
 */
create table if not exists public.character_embeddings (
  character_id uuid primary key references public.assets(id) on delete cascade,
  description_embedding vector(1024),
  personality_embedding vector(1024),
  updated_at timestamp default now()
);

alter table public.character_embeddings enable row level security;

/*
 * Read access delegates to the parent row rather than restating the
 * account check. Postgres applies the parent's own RLS inside this
 * subquery, so an embedding is visible exactly when its episode or asset
 * is — one definition of "who can see this", not two that can drift.
 *
 * There are deliberately no write policies. Embeddings are generated by a
 * background worker with no user session, which uses the service role and
 * bypasses RLS; a user has no reason to write them directly.
 */
create policy "episode_embeddings_read" on public.episode_embeddings
  for select
  to authenticated using (
    exists (
      select 1 from public.episodes e
      where e.id = episode_embeddings.episode_id
    )
  );

create policy "character_embeddings_read" on public.character_embeddings
  for select
  to authenticated using (
    exists (
      select 1 from public.assets a
      where a.id = character_embeddings.character_id
    )
  );

revoke all on public.episode_embeddings from authenticated, anon;
revoke all on public.character_embeddings from authenticated, anon;

grant select on public.episode_embeddings to authenticated;
grant select on public.character_embeddings to authenticated;
