/*
 * -------------------------------------------------------
 * Section: Semantic search embeddings
 * Vector embeddings for episodes and characters, used by semantic
 * similarity search.
 *
 * These tables were originally created in
 * migrations/20251213000000_add_voyage_embeddings.sql with no counterpart
 * here. `config.toml` sets schema_paths = ["./schemas/*.sql"], so `db diff`
 * treated them as objects that ought not to exist and would have proposed
 * dropping them. They are declared here so the declarative schema and the
 * database agree.
 *
 * They were also created without RLS. Every table in `public` grants
 * `authenticated` full DML by default, so RLS is the only thing scoping a
 * table to its tenant — which meant any signed-in user of any account could
 * read, modify, delete or truncate every account's embeddings.
 * -------------------------------------------------------
 */

create extension if not exists vector;

/*
 * Episode embeddings
 */
create table if not exists public.episode_embeddings (
  episode_id uuid primary key references public.episodes(id) on delete cascade,
  premise_embedding vector(1024),
  story_embedding vector(1024),
  updated_at timestamp default now(),
  -- KB-35: written by the LLM worker on read, keyed by content_hash; the
  -- two columns above predate it and have no writer.
  embedding vector(1024),
  content_hash text,
  model text
);

alter table public.episode_embeddings enable row level security;

/*
 * Character embeddings. `character_id` references assets, not a characters
 * table — characters are assets in this schema.
 */
create table if not exists public.character_embeddings (
  character_id uuid primary key references public.assets(id) on delete cascade,
  description_embedding vector(1024),
  personality_embedding vector(1024),
  updated_at timestamp default now()
);

alter table public.character_embeddings enable row level security;

/*
 * Read access delegates to the parent row rather than restating the
 * account check. Postgres applies the parent's own RLS inside this
 * subquery, so an embedding is visible exactly when its episode or asset
 * is — one definition of "who can see this", not two that can drift.
 *
 * There are deliberately no write policies. Embeddings are generated by a
 * background worker with no user session, which uses the service role and
 * bypasses RLS; a user has no reason to write them directly.
 */
create policy "episode_embeddings_read" on public.episode_embeddings
  for select
  to authenticated using (
    exists (
      select 1 from public.episodes e
      where e.id = episode_embeddings.episode_id
    )
  );

create policy "character_embeddings_read" on public.character_embeddings
  for select
  to authenticated using (
    exists (
      select 1 from public.assets a
      where a.id = character_embeddings.character_id
    )
  );

revoke all on public.episode_embeddings from authenticated, anon;
revoke all on public.character_embeddings from authenticated, anon;

grant select on public.episode_embeddings to authenticated;
grant select on public.character_embeddings to authenticated;

/*
 * KB-35: the most similar of a window of episodes to a query, within one
 * project and one model. Service role only (the LLM worker).
 */
create or replace function public.match_episode_embeddings(
  query_embedding vector(1024),
  target_project_id uuid,
  candidate_episode_ids uuid[],
  embedding_model text,
  match_count integer default 3,
  min_similarity double precision default 0.5
)
returns table (episode_id uuid, similarity double precision)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    ee.episode_id,
    1 - (ee.embedding <=> query_embedding) as similarity
  from public.episode_embeddings ee
  join public.episodes e on e.id = ee.episode_id
  where e.project_id = target_project_id
    and e.deleted_at is null
    and ee.episode_id = any (candidate_episode_ids)
    and ee.model = embedding_model
    and ee.embedding is not null
    and 1 - (ee.embedding <=> query_embedding) >= min_similarity
  order by ee.embedding <=> query_embedding, ee.episode_id
  limit greatest(match_count, 0);
$$;

revoke all on function public.match_episode_embeddings(
  vector, uuid, uuid[], text, integer, double precision
) from public, anon, authenticated;

grant execute on function public.match_episode_embeddings(
  vector, uuid, uuid[], text, integer, double precision
) to service_role;
