import { SitePageHeader } from '~/(marketing)/_components/site-page-header';
import { createI18nServerInstance } from '~/lib/i18n/i18n.server';
import { withI18n } from '~/lib/i18n/with-i18n';

export async function generateMetadata() {
  const { t } = await createI18nServerInstance();

  return {
    title: t('marketing:termsOfService'),
  };
}

async function TermsOfServicePage() {
  const { t } = await createI18nServerInstance();
  const lastUpdated = 'January 7, 2025';
  const companyName = 'Around AI Limited';
  const productName = 'StoryBook';
  const website = 'storybook.digital';
  const contactEmail = 'legal@storybook.digital';

  return (
    <div>
      <SitePageHeader
        title={t(`marketing:termsOfService`)}
        subtitle={t(`marketing:termsOfServiceDescription`)}
      />

      <div className="container mx-auto max-w-4xl px-4 py-8">
        <div className="prose prose-slate dark:prose-invert max-w-none">
          <p className="text-muted-foreground text-sm">
            Last updated: {lastUpdated}
          </p>

          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using {productName} (&quot;the Service&quot;), operated by {companyName}
            (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), you agree to be bound by these Terms of Service
            (&quot;Terms&quot;). If you disagree with any part of these terms, you may not access the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            {productName} is an AI-powered content creation platform that provides:
          </p>
          <ul>
            <li><strong>Story Development:</strong> AI-assisted story generation, screenplay editing, and character/location management</li>
            <li><strong>Visual Production:</strong> AI video generation using third-party providers (Kling, Hailuo, Runway)</li>
            <li><strong>Audio Production:</strong> AI voice synthesis and music generation (ElevenLabs, PlayHT, Suno)</li>
            <li><strong>Publishing:</strong> Multi-platform publishing to YouTube, TikTok, Instagram, Facebook, Twitter, and LinkedIn</li>
            <li><strong>Analytics:</strong> Performance tracking across connected platforms</li>
            <li><strong>Team Collaboration:</strong> Multi-user workspaces with role-based permissions</li>
          </ul>

          <h2>3. Account Registration</h2>
          <h3>3.1 Eligibility</h3>
          <p>
            You must be at least 18 years old or the age of legal majority in your jurisdiction
            to use the Service. By creating an account, you represent that you meet this requirement.
          </p>
          <h3>3.2 Account Security</h3>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials
            and for all activities that occur under your account. You agree to notify us immediately
            of any unauthorized access or security breach.
          </p>
          <h3>3.3 Account Types</h3>
          <p>
            We offer personal accounts and team accounts. Team account owners are responsible for
            the actions of all team members invited to their workspace.
          </p>

          <h2>4. User Content</h2>
          <h3>4.1 Your Content</h3>
          <p>
            You retain all intellectual property rights to content you create using the Service
            (&quot;User Content&quot;), including stories, characters, screenplays, and generated media.
            By using the Service, you grant us a limited license to process, store, and display
            your content solely for the purpose of providing the Service.
          </p>
          <h3>4.2 AI-Generated Content</h3>
          <p>
            Content generated by AI tools within the Service (&quot;Generated Content&quot;) is subject
            to the terms of the underlying AI providers. You acknowledge that:
          </p>
          <ul>
            <li>Generated Content may not be unique and similar content may be generated for other users</li>
            <li>You are responsible for reviewing Generated Content for accuracy and appropriateness</li>
            <li>Generated Content should be reviewed before commercial use</li>
          </ul>
          <h3>4.3 Prohibited Content</h3>
          <p>You agree not to create, upload, or distribute content that:</p>
          <ul>
            <li>Is illegal, harmful, threatening, abusive, harassing, defamatory, or discriminatory</li>
            <li>Infringes on intellectual property rights of others</li>
            <li>Contains child sexual abuse material (CSAM) or exploits minors</li>
            <li>Contains malware, viruses, or other harmful code</li>
            <li>Impersonates any person or entity</li>
            <li>Violates the terms of connected third-party platforms</li>
          </ul>

          <h2>5. Third-Party Platform Integrations</h2>
          <h3>5.1 Platform Connections</h3>
          <p>
            The Service allows you to connect your accounts on third-party platforms
            (YouTube, TikTok, Instagram, Facebook, Twitter, LinkedIn). By connecting these accounts,
            you authorize us to access and interact with these platforms on your behalf according
            to the permissions you grant.
          </p>
          <h3>5.2 Platform Terms</h3>
          <p>
            When publishing content to third-party platforms, you must comply with their respective
            terms of service. We are not responsible for actions taken by third-party platforms
            regarding your content or account.
          </p>

          <h2>6. Payment and Billing</h2>
          <h3>6.1 Subscription Plans</h3>
          <p>
            Access to certain features requires a paid subscription. Pricing and plan details
            are available on our website. All fees are quoted in USD unless otherwise specified.
          </p>
          <h3>6.2 Payment Processing</h3>
          <p>
            We use third-party payment processors (Stripe and/or Lemon Squeezy) to handle
            transactions. By providing payment information, you agree to their respective terms
            and privacy policies.
          </p>
          <h3>6.3 Cancellation and Refunds</h3>
          <p>
            You may cancel your subscription at any time. Cancellation takes effect at the end
            of your current billing period. Refunds are provided at our sole discretion.
          </p>
          <h3>6.4 AI Credit Usage</h3>
          <p>
            Certain AI features (video generation, voice synthesis) consume credits. Unused
            credits may expire according to your plan terms. We reserve the right to modify
            credit allocation and pricing with reasonable notice.
          </p>

          <h2>7. Intellectual Property</h2>
          <h3>7.1 Our Property</h3>
          <p>
            The Service, including its original code, features, functionality, design, and
            branding, is owned by {companyName} and protected by intellectual property laws.
            You may not copy, modify, or create derivative works based on the Service.
          </p>
          <h3>7.2 Feedback</h3>
          <p>
            If you provide feedback, suggestions, or ideas about the Service, you grant us
            a perpetual, irrevocable, royalty-free license to use such feedback for any purpose.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, {companyName.toUpperCase()} SHALL NOT BE LIABLE
            FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS
            OF PROFITS, DATA, USE, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF
            THE SERVICE.
          </p>
          <p>
            OUR TOTAL LIABILITY FOR ALL CLAIMS RELATED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT
            PAID BY YOU TO US DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
          </p>

          <h2>9. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND,
            EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
          <p>
            We do not warrant that:
          </p>
          <ul>
            <li>The Service will be uninterrupted or error-free</li>
            <li>AI-generated content will be accurate, appropriate, or suitable for your purposes</li>
            <li>Third-party platform integrations will always be available</li>
            <li>Your content will not be lost or corrupted</li>
          </ul>

          <h2>10. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless {companyName}, its officers,
            directors, employees, and agents from any claims, damages, losses, or expenses
            (including reasonable legal fees) arising from:
          </p>
          <ul>
            <li>Your use of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your violation of any third-party rights</li>
            <li>Content you create or publish through the Service</li>
          </ul>

          <h2>11. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior notice,
            for any reason, including breach of these Terms. Upon termination:
          </p>
          <ul>
            <li>Your right to use the Service will immediately cease</li>
            <li>You may request export of your content within 30 days</li>
            <li>We may delete your data after a reasonable retention period</li>
          </ul>

          <h2>12. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will notify you of
            material changes via email or through the Service. Continued use of the Service
            after changes constitutes acceptance of the new Terms.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by the laws of India, without regard to conflict
            of law principles. Any disputes shall be resolved in the courts of India.
          </p>

          <h2>14. Contact Us</h2>
          <p>
            If you have questions about these Terms, please contact us at:
          </p>
          <ul>
            <li>Email: <a href={`mailto:${contactEmail}`}>{contactEmail}</a></li>
            <li>Website: <a href={`https://${website}`}>{website}</a></li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default withI18n(TermsOfServicePage);
