#!/usr/bin/env bash
#
# Local environment: Supabase, ClickHouse and the vendor sandbox on this
# machine.
#
# Exists because the analytics pipeline could not be observed at all
# otherwise. Production runs with CLICKHOUSE_ENABLED=false, where every read
# returns [] and every write is a no-op, and the unit suite mocks the
# ClickHouse client so it never executes SQL. Between the two, a query the
# server rejects outright can pass CI and reach main — which is exactly what
# happened.
#
#   ./scripts/local-env.sh up       start all three, apply migrations
#   ./scripts/local-env.sh verify   run every ClickHouse query for real
#   ./scripts/local-env.sh status
#   ./scripts/local-env.sh down
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/vendor-sandbox.sh
. "$ROOT/scripts/lib/vendor-sandbox.sh"
ENV_FILE="$ROOT/deployment/config/local.env"
CH_CONTAINER="storybook-clickhouse"

# Docker Desktop does not always put its CLI on PATH.
if ! command -v docker > /dev/null 2>&1; then
  for candidate in "$HOME/.docker/bin" /Applications/Docker.app/Contents/Resources/bin; do
    if [ -x "$candidate/docker" ]; then
      export PATH="$candidate:$PATH"
      break
    fi
  done
fi

if ! command -v docker > /dev/null 2>&1; then
  echo "docker not found. Start Docker Desktop, or add its CLI to PATH:"
  echo '  export PATH="$HOME/.docker/bin:$PATH"'
  exit 1
fi

# Pinned to the CI service container's version. This is load-bearing: 24.x
# rejects a query parameter inside a window frame where 25+ accepts one, so
# a newer local ClickHouse would pass a query that CI and an older
# production instance reject.
CH_IMAGE="clickhouse/clickhouse-server:24.8-alpine"

# deployment/config is a git submodule, so local.env is not committed with
# this repo. It carries no secrets — the Supabase keys are the CLI's fixed
# local-development keys and the ClickHouse password is set by the container
# started below — so it is generated on demand instead, from whatever
# `supabase status` reports.
write_env_file() {
  if [ -f "$ENV_FILE" ]; then
    return 0
  fi

  echo "==> Generating $ENV_FILE"

  local anon service
  anon=$(cd "$ROOT/apps/web" && supabase status -o env 2>/dev/null | grep '^ANON_KEY=' | cut -d= -f2- | tr -d '"')
  service=$(cd "$ROOT/apps/web" && supabase status -o env 2>/dev/null | grep '^SERVICE_ROLE_KEY=' | cut -d= -f2- | tr -d '"')

  if [ -z "$anon" ] || [ -z "$service" ]; then
    echo "Could not read local Supabase keys — is 'supabase start' finished?"
    return 1
  fi

  mkdir -p "$(dirname "$ENV_FILE")"
  cat > "$ENV_FILE" <<ENVEOF
# Generated by scripts/local-env.sh. Safe to delete and regenerate.
DEPLOY_TARGET=local
NODE_ENV=development
NEXT_PUBLIC_SITE_URL=http://localhost:3000

NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:55321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
SUPABASE_SERVICE_ROLE_KEY=${service}
SUPABASE_DB_URL=postgresql://postgres:postgres@127.0.0.1:55322/postgres
SUPABASE_DB_WEBHOOK_SECRET=local-webhook-secret

# Enabled, unlike production — with it false every read returns [] and every
# write is a no-op, so nothing about the pipeline can be observed.
CLICKHOUSE_ENABLED=true
CLICKHOUSE_HOST=http://localhost:8123
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=local
CLICKHOUSE_DB=default

DATABASE_PROVIDER=supabase
AUTH_PROVIDER=supabase
STORAGE_PROVIDER=supabase
EMAIL_PROVIDER=nodemailer
QUEUE_PROVIDER=memory
CACHE_PROVIDER=memory

EMAIL_HOST=127.0.0.1
EMAIL_PORT=55325
EMAIL_USER=local
EMAIL_PASSWORD=local
EMAIL_SENDER=local@storybook.test

CRON_SECRET=local-cron-secret
ENVEOF
}

load_env() {
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
}

wait_for_clickhouse() {
  for _ in $(seq 1 60); do
    if curl -sf "http://localhost:8123/ping" > /dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "ClickHouse did not become ready in 120s"
  return 1
}

case "${1:-}" in
  up)
    echo "==> Supabase"
    (cd "$ROOT/apps/web" && supabase start)

    echo "==> ClickHouse ($CH_IMAGE)"
    if docker ps -a --format '{{.Names}}' | grep -qx "$CH_CONTAINER"; then
      docker start "$CH_CONTAINER" > /dev/null
    else
      docker run -d --name "$CH_CONTAINER" \
        -e CLICKHOUSE_USER=default \
        -e CLICKHOUSE_PASSWORD=local \
        -e CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 \
        -p 8123:8123 "$CH_IMAGE" > /dev/null
    fi

    wait_for_clickhouse
    echo "    $(curl -s 'http://localhost:8123/?user=default&password=local&query=SELECT%20version()')"

    write_env_file
    ensure_sandbox_env "$ENV_FILE"

    echo "==> ClickHouse migrations"
    load_env
    (cd "$ROOT" && pnpm --filter @kit/clickhouse migrate)

    echo "==> Vendor sandbox (AI vendors FILM-1803, social platforms FILM-1802)"
    start_sandbox "$ROOT"

    # YouTube and Meta read their OAuth client from oauth_app_credentials,
    # encrypted with the app's key; the others read the env block above.
    echo "==> Sandbox OAuth clients (FILM-1802)"
    (cd "$ROOT/apps/vendor-sandbox" && pnpm --silent seed-credentials)

    echo
    echo "Ready. Env file: deployment/config/local.env"
    ;;

  verify)
    write_env_file
    load_env
    wait_for_clickhouse

    # Idempotent, and it means a fresh container reports real results rather
    # than 45 "unknown table" failures that look like query bugs.
    echo "==> ClickHouse migrations"
    (cd "$ROOT" && pnpm --filter @kit/clickhouse migrate > /dev/null)

    echo "==> ClickHouse: every query and insert, for real"
    (cd "$ROOT" && pnpm --filter @kit/clickhouse verify)

    echo
    echo "==> Supabase: schema reachable"
    tables=$(curl -sf \
      -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
      -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
      -H "Prefer: count=exact" -H "Range: 0-0" \
      -I "$NEXT_PUBLIC_SUPABASE_URL/rest/v1/accounts?select=id" \
      | grep -i content-range | tr -d '\r' || true)
    echo "    accounts ${tables:-unreachable}"
    ;;

  status)
    load_env
    echo "ClickHouse: $(curl -s "http://localhost:8123/?user=$CLICKHOUSE_USER&password=$CLICKHOUSE_PASSWORD&query=SELECT%20version()" || echo 'down')"
    (cd "$ROOT/apps/web" && supabase status 2>&1 | head -3)
    sandbox_status "$ROOT"
    ;;

  down)
    echo "==> Vendor sandbox"
    stop_sandbox "$ROOT"
    echo "==> ClickHouse"
    docker rm -f "$CH_CONTAINER" > /dev/null 2>&1 || true
    echo "==> Supabase"
    (cd "$ROOT/apps/web" && supabase stop)
    ;;

  *)
    echo "usage: ./scripts/local-env.sh {up|verify|status|down}"
    exit 1
    ;;
esac
