import 'server-only';

import { google } from 'googleapis';

import { vendorUrl } from '@kit/shared/vendors';

import { YouTubeAnalyticsScopeError } from './youtube-analytics';

/**
 * Report types this integration maintains per YouTube connection.
 *
 * - channel_basic_a3: per-video per-day core metrics (views, engagement,
 *   watch time, engaged_views)
 * - channel_combined_a3: core metrics with playback/traffic/device
 *   dimensions (used for cross-checks)
 * - channel_traffic_source_a3: per-video per-day traffic sources
 * - channel_reach_combined_a1: thumbnail impressions + CTR (added to the
 *   Reporting API on 2026-01-15)
 */
export const YOUTUBE_REPORT_TYPES = [
  'channel_basic_a3',
  'channel_combined_a3',
  'channel_traffic_source_a3',
  'channel_reach_combined_a1',
] as const;

export type YouTubeReportTypeId = (typeof YOUTUBE_REPORT_TYPES)[number];

export interface YouTubeReportJob {
  jobId: string;
  reportTypeId: string;
}

export interface YouTubeReport {
  reportId: string;
  createTime: string;
  startTime: string;
  endTime: string;
  downloadUrl: string;
}

function isScopeMissingError(error: unknown): boolean {
  if (error instanceof Error) {
    const message = error.message.toLowerCase();
    return (
      message.includes('forbidden') ||
      message.includes('insufficientpermissions') ||
      message.includes('access denied') ||
      message.includes('request had insufficient authentication scopes')
    );
  }
  return false;
}

/**
 * YouTube Reporting API (Bulk Reports) provider.
 *
 * Bulk report jobs generate daily CSV reports asynchronously (~48h latency)
 * with no additional API quota per data row, making them the authoritative
 * per-video per-day source. Uses the same yt-analytics.readonly scope as
 * the targeted-queries provider.
 */
export class YouTubeReportingProvider {
  private reporting;

  constructor(accessToken: string) {
    const oauth2Client = new google.auth.OAuth2();
    oauth2Client.setCredentials({ access_token: accessToken });
    this.reporting = google.youtubereporting({
      version: 'v1',
      auth: oauth2Client,
      rootUrl: vendorUrl('youtube-reporting'),
    });
  }

  /**
   * Lists the report types the channel can create jobs for.
   */
  async listReportTypes(): Promise<string[]> {
    try {
      const response = await this.reporting.reportTypes.list({
        pageSize: 100,
      });
      return (response.data.reportTypes ?? [])
        .map((type) => type.id ?? '')
        .filter(Boolean);
    } catch (error) {
      if (isScopeMissingError(error)) {
        throw new YouTubeAnalyticsScopeError();
      }
      throw error;
    }
  }

  /**
   * Lists the channel's existing report jobs.
   */
  async listJobs(): Promise<YouTubeReportJob[]> {
    try {
      const response = await this.reporting.jobs.list({ pageSize: 100 });
      return (response.data.jobs ?? [])
        .filter((job) => job.id && job.reportTypeId)
        .map((job) => ({
          jobId: job.id!,
          reportTypeId: job.reportTypeId!,
        }));
    } catch (error) {
      if (isScopeMissingError(error)) {
        throw new YouTubeAnalyticsScopeError();
      }
      throw error;
    }
  }

  /**
   * Creates a report job for the given report type.
   */
  async createJob(reportTypeId: string): Promise<YouTubeReportJob> {
    try {
      const response = await this.reporting.jobs.create({
        requestBody: {
          reportTypeId,
          name: `storybook-${reportTypeId}`,
        },
      });

      if (!response.data.id) {
        throw new Error(`Job creation returned no id for ${reportTypeId}`);
      }

      return { jobId: response.data.id, reportTypeId };
    } catch (error) {
      if (isScopeMissingError(error)) {
        throw new YouTubeAnalyticsScopeError();
      }
      throw error;
    }
  }

  /**
   * Lists reports generated by a job, newest first, optionally only those
   * created after the given watermark.
   */
  async listReports(
    jobId: string,
    createdAfter?: string,
  ): Promise<YouTubeReport[]> {
    const reports: YouTubeReport[] = [];
    let pageToken: string | undefined;

    try {
      do {
        const response = await this.reporting.jobs.reports.list({
          jobId,
          createdAfter,
          pageToken,
          pageSize: 50,
        });

        for (const report of response.data.reports ?? []) {
          if (!report.id || !report.downloadUrl) continue;
          reports.push({
            reportId: report.id,
            createTime: report.createTime ?? '',
            startTime: report.startTime ?? '',
            endTime: report.endTime ?? '',
            downloadUrl: report.downloadUrl,
          });
        }

        pageToken = response.data.nextPageToken ?? undefined;
      } while (pageToken);

      return reports.sort((a, b) => a.createTime.localeCompare(b.createTime));
    } catch (error) {
      if (isScopeMissingError(error)) {
        throw new YouTubeAnalyticsScopeError();
      }
      throw error;
    }
  }

  /**
   * Downloads a report's CSV content.
   */
  async downloadReport(downloadUrl: string): Promise<string> {
    const response = await this.reporting.media.download(
      { resourceName: extractResourceName(downloadUrl) },
      { responseType: 'text' },
    );

    return String(response.data ?? '');
  }
}

/**
 * The media.download resourceName is the path portion of the report's
 * downloadUrl: .../v1/media/{resourceName}?alt=media
 */
function extractResourceName(downloadUrl: string): string {
  const match = /\/v1\/media\/(.+?)(\?|$)/.exec(downloadUrl);
  return match?.[1] ?? downloadUrl;
}

export function createYouTubeReportingProvider(
  accessToken: string,
): YouTubeReportingProvider {
  return new YouTubeReportingProvider(accessToken);
}
