#!/usr/bin/env python3
"""Every registered stage's real commit plan, applied through the database.

FILM-1903: a stage's commit is a plan that apply_generation_commit applies in
one transaction. The unit matrix proves each stage builds one plan and writes
nothing outside it; this proves each of those plans is one the function
accepts and applies: the allowlist, the filters, the merges, the references
and the project scope, against the repo's migrations.

  cd packages/features/generation
  CAPTURE_COMMIT_PLANS=/tmp/plans.json npx vitest run __tests__/stage-matrix.test.ts
  for mode in server external; do
    python3 tooling/generation/commit-plans-pgtap.py /tmp/plans.json $mode \
      > apps/web/supabase/tests/database/apply-generation-commit-stages-$mode.test.sql
  done

One file per mode, each its own transaction: the two modes write the same
rows, and the second would collide with the first (a translation of the
same lines into the same language, refused by its unique key).

Regenerate it when a stage's commit changes. The rows the plans name (the
fixtures' project, episodes, season, assets, dialogue lines and users) are
seeded with session_replication_role = replica, which skips their own
parents; every plan is then applied with constraints and triggers on.
"""
import json
import re
import sys

UUID = re.compile(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
ACCOUNT = '11111111-1111-4111-8111-111111111111'


def lit(text):
    return "'" + text.replace("'", "''") + "'"


def ids_under(value, keys, found):
    if isinstance(value, dict):
        for key, item in value.items():
            if key in keys and isinstance(item, str) and UUID.match(item):
                found.setdefault(key, set()).add(item)
            ids_under(item, keys, found)
    elif isinstance(value, list):
        for item in value:
            ids_under(item, keys, found)
    return found


def main(path, mode):
    captured = [c for c in json.load(open(path)) if c['mode'] == mode]
    applied = [c for c in captured if c['plans']]

    project = {c['lock']['projectId'] for c in captured} - {None}
    assert len(project) == 1, project
    project = project.pop()

    episodes = {c['lock']['id'] for c in captured if c['lock']['type'] == 'episode'}
    seasons = {c['lock']['id'] for c in captured if c['lock']['type'] == 'season'}
    refs = ids_under([c['plans'] for c in captured], {
        'created_by', 'character_asset_id', 'character_id', 'source_dialogue_id',
        'season_id', 'established_in', 'opened_at',
    }, {})
    users = refs.get('created_by', set())
    assets = refs.get('character_asset_id', set()) | refs.get('character_id', set())
    lines = refs.get('source_dialogue_id', set())
    seasons |= refs.get('season_id', set())
    episodes |= refs.get('established_in', set()) | refs.get('opened_at', set())
    dialogue_episode = next(
        c['lock']['id'] for c in captured if c['stage'] == 'dialogue_translation')

    out = []
    w = out.append
    w('begin;')
    w('create extension "basejump-supabase_test_helpers" version \'0.0.6\';')
    w('')
    w(f'select plan({len(applied) * 2});')
    w('')
    w('-- GENERATED by tooling/generation/commit-plans-pgtap.py from the plans the')
    w('-- unit matrix (packages/features/generation/__tests__/stage-matrix.test.ts,')
    w("-- 'every registered stage commits through one plan') records: every")
    w(f"-- registered stage's real commit plan in {mode} mode, applied")
    w('-- through apply_generation_commit and committing its run (FILM-1901')
    w('-- criterion 4, FILM-1903). Do not edit by hand; regenerate.')
    w('')
    w("select makerkit.set_identifier('owner', 'owner@storybook.dev');")
    w('set local role postgres;')
    w('')
    w("-- The fixtures' rows, without their own parents")
    w('set local session_replication_role = replica;')
    for user in sorted(users):
        w(f"insert into auth.users (id, email) values ({lit(user)}, {lit(user[:8] + '@stages.test')}) on conflict do nothing;")
    w(f"insert into public.accounts (id, name, slug, is_personal_account, primary_owner_user_id) values ({lit(ACCOUNT)}, 'Stages', 'stages-txn', false, tests.get_supabase_uid('owner'));")
    w(f"insert into public.projects (id, account_id, name, status) values ({lit(project)}, {lit(ACCOUNT)}, 'Stages', 'active');")
    for season in sorted(seasons):
        w(f"insert into public.seasons (id, project_id, number, name) values ({lit(season)}, {lit(project)}, 1, 'Season');")
    for number, episode in enumerate(sorted(episodes), start=900):
        w(f"insert into public.episodes (id, project_id, number, title, story_data, metadata) values ({lit(episode)}, {lit(project)}, {number}, 'Episode', '{{}}'::jsonb, '{{}}'::jsonb);")
    for asset in sorted(assets):
        w(f"insert into public.assets (id, project_id, type, name) values ({lit(asset)}, {lit(project)}, 'character', {lit('Asset ' + asset[:8])});")
    for sequence, line in enumerate(sorted(lines), start=1):
        w(f"insert into public.dialogue_lines (id, episode_id, text, sequence_number, scene_number, language, status) values ({lit(line)}, {lit(dialogue_episode)}, 'Line', {sequence}, 1, 'en', 'pending');")
    w('set local session_replication_role = origin;')
    w('')
    w('select tests.authenticate_as_service_role();')

    for index, case in enumerate(applied):
        lock = case['lock']
        name = f"{case['stage']} ({case['mode']})"
        plan = json.dumps(case['plans'][0], separators=(',', ':'), sort_keys=True)
        w('')
        w(f'-- {name}')
        w(f"select set_config('st.run', (public.open_generation_run(p_account_id := {lit(ACCOUNT)}, p_project_id := {lit(project)}, p_target_type := {lit(lock['type'])}, p_target_id := {lit(lock['id'])}, p_stage := {lit(case['stage'])}, p_mode := {lit(case['mode'])}, p_input := '{{}}'::jsonb, p_origin := '{{}}'::jsonb, p_created_by := tests.get_supabase_uid('owner')) -> 'run' ->> 'id'), true);")
        w(f"select is((public.apply_generation_commit(current_setting('st.run')::uuid, {lit(plan)}::jsonb) ->> 'ok'), 'true', {lit(name + ' applies its plan')});")
        w(f"select is((select status from public.generation_runs where id = current_setting('st.run')::uuid), 'committed', {lit(name + ' commits its run')});")

    w('')
    w('select * from finish();')
    w('rollback;')
    print('\n'.join(out))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
