import 'server-only';

import { z } from 'zod';

import { McpToolError } from '../../../errors';
import { defineTool } from '../../../registry';
import { READ_ONLY, requireTeamScope } from './shared';

/**
 * Saved Gemini insights (FILM-808): what the insights handler cached for a
 * project, newest first. Read under the member policy FILM-1906 part A
 * added (`analytics_insights_cache_read`), on the principal's client: a
 * project outside the team has no rows, and is refused above anyway.
 */
export const getSavedInsights = defineTool({
  name: 'get_saved_insights',
  title: 'Saved insights',
  description:
    'The AI insights saved for a project, newest first: each entry is the insights the dashboard showed for one input set, with when it was generated. Cached results only; nothing is generated by this call.',
  inputSchema: {
    projectId: z.string().uuid(),
    limit: z.number().int().min(1).max(50).default(10),
  },
  scope: 'studio:read',
  annotations: READ_ONLY,
  async handler(input, context) {
    await requireTeamScope(context, { projectId: input.projectId });

    const { data, error } = await context.principal.supabase
      .from('analytics_insights_cache')
      .select('project_id, input_hash, insights, created_at')
      .eq('project_id', input.projectId)
      .order('created_at', { ascending: false })
      .order('input_hash')
      .limit(input.limit);

    if (error) {
      throw new McpToolError('INTERNAL', 'Could not read the saved insights.');
    }

    return {
      structuredContent: {
        projectId: input.projectId,
        data: data.map((row) => ({
          inputHash: row.input_hash,
          generatedAt: row.created_at,
          insights: row.insights,
        })),
      },
    };
  },
});
